MCU = atmega32u4
BOOTLOADER = caterina
BOOTMAGIC_ENABLE = lite
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no

SLEEP_LED_ENABLE = no
NKRO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = yes
BLUETOOTH_ENABLE = no
AUDIO_ENABLE = no
SPLIT_KEYBOARD = yes
OLED_DRIVER_ENABLE = yes

GRAVE_ESC_ENABLE = no
LTO_ENABLE = yes
WPM_ENABLE = yes
SPACE_CADET_ENABLE = no
UNICODEMAP_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
